"""Arena Hero benchmark platform contracts and tooling."""

from arena_hero_bench.agent_runtime import (
    AGENT_RUN_EVIDENCE_SCHEMA,
    AGENT_RUN_IMPORT_REPORT_SCHEMA,
    AgentRunEvidence,
    AgentRuntimeImportError,
    import_agent_run,
)
from arena_hero_bench.artifact_index import (
    ArtifactIndexError,
    GcCandidate,
    GcPlan,
    ManifestIssue,
    ObjectIssue,
    StaleScanError,
    StoreScan,
    build_gc_plan,
)
from arena_hero_bench.configuration import ConfigResolver, ConfigSchema, FrozenConfig
from arena_hero_bench.contestant import ContestantManifest, ContestantRegistry
from arena_hero_bench.differential import (
    DEFAULT_EXPECTED_UNKNOWN,
    REPLAY_DIFFERENTIAL_SCHEMA,
    DifferentialDimension,
    DifferentialError,
    DifferentialOutcome,
    DifferentialReport,
    DifferentialStatus,
    build_differential_run,
    canonicalize_py_agent_record,
    canonicalize_ts_legacy_record,
    classify_differential_run,
    load_py_agent_corpus,
    load_ts_legacy_corpus,
    run_differential_from_manifest,
    world_state_digest,
)
from arena_hero_bench.manifest import ArtifactManifest, ArtifactStatus, RunManifest
from arena_hero_bench.orchestration import (
    ArtifactStore,
    DistributedExecutor,
    LocalExecutor,
    RunStatus,
    ShardPlan,
    ShardResult,
    merge_shards,
)
from arena_hero_bench.performance import (
    COMPARATIVE_PERFORMANCE_EVIDENCE_SCHEMA,
    MEASUREMENT_PROTOCOL_SCHEMA,
    MINIMUM_CREDIBLE_SAMPLE_NS,
    PERFORMANCE_EVIDENCE_SCHEMA,
    REPLAY_ATTESTATION_UNATTESTED,
    REPLAY_ATTESTATION_VERIFIED,
    ComparativePerformanceEvidence,
    MeasurementProtocol,
    PerformanceEvidence,
    PerformanceMeasurementError,
    PublicEnvironment,
    ReplayArtifactResolver,
    measure_comparative_workloads,
    measure_reference_workload,
)
from arena_hero_bench.process_executor import (
    BackendProcessSpec,
    ProcessExecutor,
    ProcessExecutorError,
    reference_engine_process_executor,
)
from arena_hero_bench.storage import FilesystemArtifactStore

__all__ = [
    "AGENT_RUN_EVIDENCE_SCHEMA",
    "AGENT_RUN_IMPORT_REPORT_SCHEMA",
    "COMPARATIVE_PERFORMANCE_EVIDENCE_SCHEMA",
    "DEFAULT_EXPECTED_UNKNOWN",
    "MEASUREMENT_PROTOCOL_SCHEMA",
    "MINIMUM_CREDIBLE_SAMPLE_NS",
    "PERFORMANCE_EVIDENCE_SCHEMA",
    "REPLAY_ATTESTATION_UNATTESTED",
    "REPLAY_ATTESTATION_VERIFIED",
    "REPLAY_DIFFERENTIAL_SCHEMA",
    "AgentRunEvidence",
    "AgentRuntimeImportError",
    "ArtifactIndexError",
    "ArtifactManifest",
    "ArtifactStatus",
    "ArtifactStore",
    "BackendProcessSpec",
    "ComparativePerformanceEvidence",
    "ConfigResolver",
    "ConfigSchema",
    "ContestantManifest",
    "ContestantRegistry",
    "DifferentialDimension",
    "DifferentialError",
    "DifferentialOutcome",
    "DifferentialReport",
    "DifferentialStatus",
    "DistributedExecutor",
    "FilesystemArtifactStore",
    "FrozenConfig",
    "GcCandidate",
    "GcPlan",
    "LocalExecutor",
    "ManifestIssue",
    "MeasurementProtocol",
    "ObjectIssue",
    "PerformanceEvidence",
    "PerformanceMeasurementError",
    "ProcessExecutor",
    "ProcessExecutorError",
    "PublicEnvironment",
    "ReplayArtifactResolver",
    "RunManifest",
    "RunStatus",
    "ShardPlan",
    "ShardResult",
    "StaleScanError",
    "StoreScan",
    "build_differential_run",
    "build_gc_plan",
    "canonicalize_py_agent_record",
    "canonicalize_ts_legacy_record",
    "classify_differential_run",
    "import_agent_run",
    "load_py_agent_corpus",
    "load_ts_legacy_corpus",
    "measure_comparative_workloads",
    "measure_reference_workload",
    "merge_shards",
    "reference_engine_process_executor",
    "run_differential_from_manifest",
    "world_state_digest",
]
__version__ = "0.2.0"
