"""Preregistered research contracts and reproducible execution for Arena Hero Lab."""

from arena_hero_research.analysis import (
    DataQualityReport,
    EffectEstimate,
    MissingObservationError,
    ResearchAnalysisError,
    UndeclaredOutcomeError,
    analyze_preregistered_paired_outcomes,
    benjamini_hochberg,
    normal_approx_paired_sample_size,
    paired_effect_with_bootstrap_ci,
)
from arena_hero_research.assignment import (
    AssignmentError,
    AssignmentManifest,
    AssignmentRecord,
    AssignmentUnit,
    generate_assignments,
)
from arena_hero_research.conclusion import (
    ConclusionError,
    OutcomeConclusion,
    ResearchConclusion,
    create_research_conclusion,
)
from arena_hero_research.contracts import (
    AnalysisPlan,
    ExperimentDesign,
    Factor,
    Hypothesis,
    HypothesisDirection,
    MissingDataPolicy,
    MultipleComparisonPolicy,
    Outcome,
    OutcomeRole,
    Preregistration,
    ReplicationPlan,
    ResearchQuestion,
    ResearchRunStatus,
)
from arena_hero_research.durable import (
    DurableResearchLedger,
    DurableResearchLedgerError,
)
from arena_hero_research.execution import (
    DataRole,
    DroppedPair,
    ExecutionProvenance,
    PairedObservation,
    ReplicationError,
    ReplicationResult,
    ReplicationResultStatus,
    ReplicationTask,
    build_replication_tasks,
)
from arena_hero_research.hierarchical import (
    ClusterIdentifiabilityError,
    ClusterMissingPolicy,
    ClusterObservation,
    CrossValidationReport,
    HierarchicalFitError,
    RandomInterceptFit,
    SingularFitError,
    cross_validate_random_intercept,
    fit_random_intercept,
    fit_random_intercept_with_certificate,
    paired_to_cluster_observations,
    verify_solver_certificate,
)
from arena_hero_research.hierarchical_artifacts import (
    CrossValidationReportV1,
    CrossValidationStatus,
    DesignProfile,
    SolverCertificate,
    SolverEvaluation,
    SolverEvidenceError,
    SolverStatus,
    ValidationScope,
)
from arena_hero_research.hierarchical_evidence import (
    HierarchicalAnalysisEvidence,
    HierarchicalEvidenceError,
    analyze_hierarchical_evidence,
    commit_hierarchical_analysis_evidence,
    load_hierarchical_analysis_evidence,
)
from arena_hero_research.ledger import (
    DataUseClaim,
    DataUseLedger,
    LedgerConflictError,
    OperationLedger,
    OperationRecord,
)
from arena_hero_research.lifecycle import LifecycleError, ResearchLifecycle, ResearchPhase
from arena_hero_research.planning import (
    MonteCarloPowerResult,
    PowerPlanningError,
    simulate_monte_carlo_power,
)
from arena_hero_research.provenance import (
    EnvironmentProvenance,
    EnvironmentSnapshot,
    ProvenanceError,
    SoftwareBillOfMaterials,
    SoftwareComponent,
)
from arena_hero_research.replication import (
    MergedOutcomePairs,
    ReplicationDroppedPair,
    ReplicationMerge,
    ReplicationOutcomeEvidence,
    ReplicationQualityError,
    merge_replications,
)
from arena_hero_research.results import (
    AnalysisPlanMismatchError,
    ResearchBundleError,
    ResearchRun,
    ResultBundle,
)
from arena_hero_research.runner import ReplicationExecutor, ReplicationRunner
from arena_hero_research.statistics import arithmetic_mean
from arena_hero_research.storage import (
    FilesystemResearchLedgerStorage,
    FrozenResearchRecord,
    LedgerCorruptionError,
    LedgerStorageError,
    ResearchLedgerState,
    ResearchLedgerStorage,
    ResearchLedgerTransaction,
    ResearchRecordKind,
    TornLedgerTailError,
    TornTailRecovery,
)

__all__ = [
    "AnalysisPlan",
    "AnalysisPlanMismatchError",
    "AssignmentError",
    "AssignmentManifest",
    "AssignmentRecord",
    "AssignmentUnit",
    "ClusterIdentifiabilityError",
    "ClusterMissingPolicy",
    "ClusterObservation",
    "ConclusionError",
    "CrossValidationReport",
    "CrossValidationReportV1",
    "CrossValidationStatus",
    "DataQualityReport",
    "DataRole",
    "DataUseClaim",
    "DataUseLedger",
    "DesignProfile",
    "DroppedPair",
    "DurableResearchLedger",
    "DurableResearchLedgerError",
    "EffectEstimate",
    "EnvironmentProvenance",
    "EnvironmentSnapshot",
    "ExecutionProvenance",
    "ExperimentDesign",
    "Factor",
    "FilesystemResearchLedgerStorage",
    "FrozenResearchRecord",
    "HierarchicalAnalysisEvidence",
    "HierarchicalEvidenceError",
    "HierarchicalFitError",
    "Hypothesis",
    "HypothesisDirection",
    "LedgerConflictError",
    "LedgerCorruptionError",
    "LedgerStorageError",
    "LifecycleError",
    "MergedOutcomePairs",
    "MissingDataPolicy",
    "MissingObservationError",
    "MonteCarloPowerResult",
    "MultipleComparisonPolicy",
    "OperationLedger",
    "OperationRecord",
    "Outcome",
    "OutcomeConclusion",
    "OutcomeRole",
    "PairedObservation",
    "PowerPlanningError",
    "Preregistration",
    "ProvenanceError",
    "RandomInterceptFit",
    "ReplicationDroppedPair",
    "ReplicationError",
    "ReplicationExecutor",
    "ReplicationMerge",
    "ReplicationOutcomeEvidence",
    "ReplicationPlan",
    "ReplicationQualityError",
    "ReplicationResult",
    "ReplicationResultStatus",
    "ReplicationRunner",
    "ReplicationTask",
    "ResearchAnalysisError",
    "ResearchBundleError",
    "ResearchConclusion",
    "ResearchLedgerState",
    "ResearchLedgerStorage",
    "ResearchLedgerTransaction",
    "ResearchLifecycle",
    "ResearchPhase",
    "ResearchQuestion",
    "ResearchRecordKind",
    "ResearchRun",
    "ResearchRunStatus",
    "ResultBundle",
    "SingularFitError",
    "SoftwareBillOfMaterials",
    "SoftwareComponent",
    "SolverCertificate",
    "SolverEvaluation",
    "SolverEvidenceError",
    "SolverStatus",
    "TornLedgerTailError",
    "TornTailRecovery",
    "UndeclaredOutcomeError",
    "ValidationScope",
    "analyze_hierarchical_evidence",
    "analyze_preregistered_paired_outcomes",
    "arithmetic_mean",
    "benjamini_hochberg",
    "build_replication_tasks",
    "commit_hierarchical_analysis_evidence",
    "create_research_conclusion",
    "cross_validate_random_intercept",
    "fit_random_intercept",
    "fit_random_intercept_with_certificate",
    "generate_assignments",
    "load_hierarchical_analysis_evidence",
    "merge_replications",
    "normal_approx_paired_sample_size",
    "paired_effect_with_bootstrap_ci",
    "paired_to_cluster_observations",
    "simulate_monte_carlo_power",
    "verify_solver_certificate",
]

__version__ = "0.2.0"
