"""Deterministic Arena Hero simulator platform contracts."""

from arena_hero_sim.backend import BackendDescriptor, SimulatorBackend
from arena_hero_sim.contracts import (
    BackendCapabilities,
    RulesetRef,
    SimulationRequest,
    SimulationResult,
    SimulationStatus,
    SimulatorConfig,
)
from arena_hero_sim.reference import (
    REFERENCE_BACKEND_ID,
    REFERENCE_ENGINE_VERSION,
    REFERENCE_FEATURES,
    REFERENCE_PROTOCOL_VERSION,
    REFERENCE_RULESET,
    ReferenceBackendPlaceholder,
    ReferenceEngineBackend,
)
from arena_hero_sim.reference_contracts import (
    REFERENCE_MOVEMENT_RULE_IDENTITY,
    REFERENCE_RULES,
    ReferenceActionKind,
    ReferenceCommand,
    ReferenceCore,
    ReferenceDirection,
    ReferenceEpisodeStatus,
    ReferenceEvent,
    ReferenceObservation,
    ReferencePlayer,
    ReferenceReplay,
    ReferenceReplayFrame,
    ReferenceRules,
    ReferenceScenario,
    ReferenceTerrain,
    ReferenceTurn,
    ReferenceUnit,
    ReferenceWorld,
)
from arena_hero_sim.reference_engine import (
    ReferenceEpisodeResult,
    ReferenceRng,
    UnsupportedReferenceSliceError,
    observe_world,
    run_reference_episode,
    settle_reference_turn,
    verify_reference_replay,
)
from arena_hero_sim.registry import BackendRegistry
from arena_hero_sim.serialization import canonical_json_bytes, content_sha256

__all__ = [
    "REFERENCE_BACKEND_ID",
    "REFERENCE_ENGINE_VERSION",
    "REFERENCE_FEATURES",
    "REFERENCE_MOVEMENT_RULE_IDENTITY",
    "REFERENCE_PROTOCOL_VERSION",
    "REFERENCE_RULES",
    "REFERENCE_RULESET",
    "BackendCapabilities",
    "BackendDescriptor",
    "BackendRegistry",
    "ReferenceActionKind",
    "ReferenceBackendPlaceholder",
    "ReferenceCommand",
    "ReferenceCore",
    "ReferenceDirection",
    "ReferenceEngineBackend",
    "ReferenceEpisodeResult",
    "ReferenceEpisodeStatus",
    "ReferenceEvent",
    "ReferenceObservation",
    "ReferencePlayer",
    "ReferenceReplay",
    "ReferenceReplayFrame",
    "ReferenceRng",
    "ReferenceRules",
    "ReferenceScenario",
    "ReferenceTerrain",
    "ReferenceTurn",
    "ReferenceUnit",
    "ReferenceWorld",
    "RulesetRef",
    "SimulationRequest",
    "SimulationResult",
    "SimulationStatus",
    "SimulatorBackend",
    "SimulatorConfig",
    "UnsupportedReferenceSliceError",
    "canonical_json_bytes",
    "content_sha256",
    "observe_world",
    "run_reference_episode",
    "settle_reference_turn",
    "verify_reference_replay",
]
__version__ = "0.2.0"
