"""Deterministic Arena Hero simulator platform contracts."""

from arena_hero_sim.backend import BackendDescriptor, SimulatorBackend
from arena_hero_sim.contracts import (
    BackendCapabilities,
    RulesetRef,
    SimulationRequest,
    SimulationResult,
    SimulationStatus,
    SimulatorConfig,
)
from arena_hero_sim.reference import (
    REFERENCE_BACKEND_ID,
    REFERENCE_ENGINE_VERSION,
    REFERENCE_FEATURES,
    REFERENCE_PROTOCOL_VERSION,
    REFERENCE_RULESET,
    ReferenceBackendPlaceholder,
    ReferenceEngineBackend,
)
from arena_hero_sim.reference_contracts import (
    REFERENCE_MOVEMENT_RULE_IDENTITY,
    REFERENCE_RULES,
    ReferenceActionKind,
    ReferenceCommand,
    ReferenceCore,
    ReferenceDirection,
    ReferenceEpisodeStatus,
    ReferenceEvent,
    ReferenceObservation,
    ReferencePlayer,
    ReferenceReplay,
    ReferenceReplayFrame,
    ReferenceRules,
    ReferenceScenario,
    ReferenceTerrain,
    ReferenceTurn,
    ReferenceUnit,
    ReferenceWorld,
)
from arena_hero_sim.reference_engine import (
    ReferenceEpisodeResult,
    ReferenceRng,
    UnsupportedReferenceSliceError,
    observe_world,
    run_reference_episode,
    settle_reference_turn,
    verify_reference_replay,
)
from arena_hero_sim.reference_workload import (
    CANONICAL_REFERENCE_WORKLOAD_ID,
    CANONICAL_REFERENCE_WORKLOAD_SHA256,
    CANONICAL_REFERENCE_WORKLOAD_VERSION,
    DIFFERENTIAL_REPORT_SCHEMA,
    REFERENCE_WORKLOAD_RUN_SCHEMA,
    DifferentialMismatch,
    DifferentialReport,
    KnownAnswer,
    ReferenceScenarioRegistry,
    ReferenceWorkloadError,
    ReferenceWorkloadRunner,
    VerifiedReferenceScenario,
    WorkloadBackendIdentity,
    WorkloadEpisodeResult,
    WorkloadRun,
    canonical_reference_scenario_registry,
    canonical_reference_workload_manifest,
    compare_workload_runs,
    run_canonical_reference_workload,
)
from arena_hero_sim.registry import BackendRegistry
from arena_hero_sim.serialization import canonical_json_bytes, content_sha256
from arena_hero_sim.workload import (
    WORKLOAD_MANIFEST_SCHEMA,
    WorkloadCase,
    WorkloadManifest,
)

__all__ = [
    "CANONICAL_REFERENCE_WORKLOAD_ID",
    "CANONICAL_REFERENCE_WORKLOAD_SHA256",
    "CANONICAL_REFERENCE_WORKLOAD_VERSION",
    "DIFFERENTIAL_REPORT_SCHEMA",
    "REFERENCE_BACKEND_ID",
    "REFERENCE_ENGINE_VERSION",
    "REFERENCE_FEATURES",
    "REFERENCE_MOVEMENT_RULE_IDENTITY",
    "REFERENCE_PROTOCOL_VERSION",
    "REFERENCE_RULES",
    "REFERENCE_RULESET",
    "REFERENCE_WORKLOAD_RUN_SCHEMA",
    "WORKLOAD_MANIFEST_SCHEMA",
    "BackendCapabilities",
    "BackendDescriptor",
    "BackendRegistry",
    "DifferentialMismatch",
    "DifferentialReport",
    "KnownAnswer",
    "ReferenceActionKind",
    "ReferenceBackendPlaceholder",
    "ReferenceCommand",
    "ReferenceCore",
    "ReferenceDirection",
    "ReferenceEngineBackend",
    "ReferenceEpisodeResult",
    "ReferenceEpisodeStatus",
    "ReferenceEvent",
    "ReferenceObservation",
    "ReferencePlayer",
    "ReferenceReplay",
    "ReferenceReplayFrame",
    "ReferenceRng",
    "ReferenceRules",
    "ReferenceScenario",
    "ReferenceScenarioRegistry",
    "ReferenceTerrain",
    "ReferenceTurn",
    "ReferenceUnit",
    "ReferenceWorkloadError",
    "ReferenceWorkloadRunner",
    "ReferenceWorld",
    "RulesetRef",
    "SimulationRequest",
    "SimulationResult",
    "SimulationStatus",
    "SimulatorBackend",
    "SimulatorConfig",
    "UnsupportedReferenceSliceError",
    "VerifiedReferenceScenario",
    "WorkloadBackendIdentity",
    "WorkloadCase",
    "WorkloadEpisodeResult",
    "WorkloadManifest",
    "WorkloadRun",
    "canonical_json_bytes",
    "canonical_reference_scenario_registry",
    "canonical_reference_workload_manifest",
    "compare_workload_runs",
    "content_sha256",
    "observe_world",
    "run_canonical_reference_workload",
    "run_reference_episode",
    "settle_reference_turn",
    "verify_reference_replay",
]
__version__ = "0.2.0"
